//VARIABLES//VARIABLES//VARIABLES//VARIABLES//VARIABLES//VARIABLES//VARIABLES//VARIABLES//VARIABLES//VARIABLES//VARIABLES






//FUNCIONES//FUNCIONES//FUNCIONES//FUNCIONES //FUNCIONES//FUNCIONES //FUNCIONES//FUNCIONES //FUNCIONES//FUNCIONES //FUNCIONES//FUNCIONES  
 








//EVENTOS//EVENTOS //EVENTOS //EVENTOS //EVENTOS //EVENTOS //EVENTOS //EVENTOS //EVENTOS  







