//FUNCIONES PARA EL SISTEMA DE COMPRAS QUE SIMULARA UNA COMPRA DE MEMBRESIA//FUNCIONES PARA EL SISTEMA DE COMPRAS QUE SIMULARA UNA COMPRA DE MEMBRESIA//FUNCIONES PARA EL SISTEMA DE COMPRAS QUE SIMULARA UNA COMPRA DE MEMBRESIA//FUNCIONES PARA EL SISTEMA DE COMPRAS QUE SIMULARA UNA COMPRA DE MEMBRESIA//FUNCIONES PARA EL SISTEMA DE COMPRAS QUE SIMULARA UNA COMPRA DE MEMBRESIA

const compra=()=>{

};

const verificarCompra=()=>{

}